development:     #
  adapter: postgresql
  encoding: unicode
  database: enterprise
  pool: 5
  username: postgres
  password: di03051999
  host: localhost
  port: 5432

test:            #
  adapter: postgresql
  encoding: unicode
  database: enterprise
  pool: 5
  username: postgres
  password: di03051999
  host: localhost
  port: 5432

production:      #
  adapter: postgresql
  encoding: unicode
  database: enterprise
  pool: 5
  username: postgres
  password: di03051999
  host: 192.168.0.50
  port: 5432
